# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives 
  随笔: /notes 
  关于: http://yaojusheng.gitee.io/resume/
  简历制作: http://yaojusheng.gitee.io/online-resume

# 是否显示目录
TOC: true
toc_number: false

# 是否自动播放音乐
autoplay: true

# 默认音乐（随机播放）
mp3: 
  - https://link.hhtjim.com/163/362081015.mp3
  - https://link.hhtjim.com/163/1370351274.mp3
  - https://link.hhtjim.com/163/4903779845.mp3
  - https://link.hhtjim.com/163/29032189.mp3
  - https://link.hhtjim.com/163/92305.mp3
  - https://link.hhtjim.com/163/1443027575.mp3
  - https://link.hhtjim.com/163/553815178.mp3
  - https://link.hhtjim.com/163/1338146196.mp3
  - https://link.hhtjim.com/163/1363205817.mp3
  - https://link.hhtjim.com/163/531295576.mp3
  - https://link.hhtjim.com/163/1383876635.mp3
  - https://link.hhtjim.com/163/1389847545.mp3
  - https://link.hhtjim.com/163/33223326.mp3
  - https://link.hhtjim.com/163/36270426.mp3
  - https://link.hhtjim.com/163/29011073.mp3
  - https://link.hhtjim.com/163/108485.mp3
  - https://link.hhtjim.com/xiami/2101032929.mp3
  - https://link.hhtjim.com/xiami/2101051069.mp3
  - https://link.hhtjim.com/xiami/2101055059.mp3
  - https://link.hhtjim.com/xiami/2101875084.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/cover/cover.jpg

# 默认文章封面图（随机调用,支持外链）
cover: 
  - /img/cover/cover.jpg
 
# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
  # facebook: /
  # twitter: /
  github: https://github.com/YaoJusheng
  csdn: "https://blog.csdn.net/weixin_41599858"
  wechat: /img/mini-weixin.jpg
  email: mailto:jusheng_yao@outlook.com

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# 备案
beian: 
    # 是否显示备案信息
    enable: false
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# 1、Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: false
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: ''
    # 应用秘钥
    clientSecret: ''
    # issue仓库名
    repo: ''
    # Github名
    owner: ''
    # Github名
    admin: ['']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: true

# 2、utteranc评论： https://utteranc.es (参数配置详见主页) 替换 gitment、gitalk
utterance:
  enable: false
  repo: ''     #仓库名字,格式：你的用户ID/仓库名称，如：blog/utterance_repo
  issue_term: 'title'            #映射配置
  theme: 'github-light'          #主题

# 3、Giteement----【国内用户建议使用这个，相对比较快】
# 关于如何集成:https://www.jianshu.com/p/f5c4633524c7
# 基于码云的评论系统(https://gitee.com/zhousiwei/giteement)
giteement:
  enable: false  # 是否启用码云评论系统
  # 是否使用官方js(false可以提升访问速度)
  remote: false
  redirect_uri:    # 应用回调地址(请和配置的第三方应用保持一致)
  # 不能更改(网上开源项目`https://github.com/Rob--W/cors-anywhere`作者提供的专门用来跨域服务器的配置)
  oauth_uri: https://cors-anywhere.herokuapp.com/https://gitee.com/oauth/token
  giteeID: yaojusheng  # 你的码云账号英文名
  # 存储评论的 repo name(需要在码云仓库创建公开仓库)
  repo: blog
  gitment_oauth:
    client_id: ''           #client ID
    client_secret: ''       #client secret

# 4、valine 评论系统，到leancloud进行注册
# https://leancloud.cn/dashboard/login.html#/signup
valine: 
  enable: false
  appid: ''  # Leancloud应用的appId
  appkey: ''          # Leancloud应用的appKey
  verify: false      # 验证码
  notify: true       # 评论回复提醒
  avatar: wavatar        # 评论列表头像样式（https://valine.js.org/avatar）mm
  placeholder: 有话要说？ # 评论框占位符
  pageSize: 10
  visitor: true
  # 是否自动展开评论框
  autoExpand: false

# 版权声明
# 版权声明type设定：0-关闭版权声明； 1-文章对应的md文件里有copyright: true属性，才有版权声明； 2-所有文章均有版权声明
copyright:
  copyright_type: 2
  licensee_url: https://creativecommons.org/licenses/by-nc-sa/4.0/        #当前应用的版权协议地址。
  licensee_name: 'CC BY-NC-SA 4.0'                                        #版权协议的名称
  licensee_alias: '知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议'       # alias别名
  # https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png
  licensee_img: /images/copyright.png    #版权协议的Logo (/images/copyright.png)
  # 版权声明自定义文本(关闭请设置为false)
  copyright_text: 

# https://github.com/willin/hexo-wordcount
# 是否开启字数统计(关闭请设置enable为false)
# 也可以单独在md文件里Front-matter设置`no_word_count: true`属性，来自定义关闭字数统计
word_count:
  enable: true
  # 只在文章详情显示(不在首页显示)
  only_article_visit: true

# 访问量统计功能(不蒜子)
busuanzi:
  enable: true
  site_visit: true  # 站点访问量显示
  article_visit: true  # 文章访问量显示

# 网站关键字
keywords: Python、PHP、Ruby开发、前端

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: ''

# 网站ico
# favicon: /images/site-icon/svg/MrYao02.svg
favicon: /img/MrYao.ico

# rss文件
rss: atom.xml
